# golangci-lint configuration
version: "2"

run:
  timeout: 5m

linters:
  default: none
  enable:
    - govet
    - staticcheck
    - unused
    - ineffassign
    - errcheck
  settings:
    govet:
      disable:
        - fieldalignment
        - copylocks
    staticcheck:
      checks:
        - "all"
        - "-QF1003"   # tagged switch - style preference
        - "-ST1000"   # package comments - too many to add now
        - "-ST1003"   # naming conventions (e.g. Sql vs SQL)
        - "-ST1020"   # function comment form
        - "-ST1021"   # type comment form
        - "-ST1022"   # var/const comment form
    errcheck:
      exclude-functions:
        # stdout/stderr print output - errors are meaningless
        - fmt.Print
        - fmt.Printf
        - fmt.Println
        - fmt.Fprint
        - fmt.Fprintf
        - fmt.Fprintln
        # color output
        - (github.com/fatih/color.Color).Fprint
        - (github.com/fatih/color.Color).Fprintf
        - (github.com/fatih/color.Color).Fprintln
        # string/bytes builders never fail
        - (*strings.Builder).WriteString
        - (*strings.Builder).WriteRune
        - (*strings.Builder).WriteByte
        - (*bytes.Buffer).WriteString
        - (*bytes.Buffer).Write
        - (*bytes.Buffer).WriteByte
        - (*bytes.Buffer).WriteRune
        # hash writes never fail
        - (hash.Hash).Write
        # cobra flags - panics on error anyway
        - (*github.com/spf13/cobra.Command).MarkFlagRequired
        # tabwriter flush to stdout is harmless
        - (*text/tabwriter.Writer).Flush
        # os.Setenv in test setup rarely fails
        - os.Setenv
        - os.Unsetenv
        # flag.Set errors are handled by cobra
        - (*flag.FlagSet).Set

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
