# golangci-lint configuration - relaxed for existing codebase
version: "2"

run:
  timeout: 5m

linters:
  default: none
  enable:
    # Only essential linters that catch real bugs
    - govet

settings:
  govet:
    disable:
      - fieldalignment
      - copylocks

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
