# golangci-lint configuration - relaxed for existing codebase
run:
  timeout: 5m
  tests: false

linters:
  disable-all: true
  enable:
    # Only essential linters that catch real bugs
    - govet
    - ineffassign

linters-settings:
  govet:
    disable:
      - fieldalignment
      - copylocks

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
